version: '3.4'

services:
  db:
    image: postgres:13.4
    hostname: postgres-13.4
    container_name: 'master-db'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGTZ: 'Europe/Kiev'
      TZ: 'Europe/Kiev'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./docker/postgres/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - lan
    command: [ "postgres", "-c", "wal_level=logical" ]

networks:
  lan:
volumes:
  db: